/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
#pragma once

//****************Русский****************//
#define TOOL_TEXT_RU                    "инструмент"
#define PREHEAT_TEXT_RU                 " нагрев"
#define MOVE_TEXT_RU                    "движение"
#define HOME_TEXT_RU                    "домой"
#define PRINT_TEXT_RU                   " печать"
#define EXTRUDE_TEXT_RU                 "экструдер"
#define LEVELING_TEXT_RU                "уровень"
#define AUTO_LEVELING_TEXT_RU           "aвтоуровень"
#define SET_TEXT_RU                     "настройки"
#define MORE_TEXT_RU                    "больше"
#define MORE_GCODE_RU                   "G-код"
#define MORE_ENTER_GCODE_RU             " введите G-код"

#define ADD_TEXT_RU                     "увеличить"
#define DEC_TEXT_RU                     "уменьшить"
#define EXTRUDER_1_TEXT_RU              "экструдер 1"
#define EXTRUDER_2_TEXT_RU              "экструдер 2"
#define HEATBED_TEXT_RU                 "стол"
#define TEXT_1C_RU                      "1° Ц"
#define TEXT_5C_RU                      "5° Ц"
#define TEXT_10C_RU                     "10° Ц"
#define CLOSE_TEXT_RU                   "выкл"

#define BACK_TEXT_RU                    "назад"

#define TOOL_PREHEAT_RU                 "нагрев"
#define TOOL_EXTRUDE_RU                 "экструдер"
#define TOOL_MOVE_RU                    "движение"
#define TOOL_HOME_RU                    "домой"
#define TOOL_LEVELING_RU                "уровень"
#define TOOL_AUTO_LEVELING_RU           "aвтоуровень"
#define TOOL_FILAMENT_RU                "замена"
#define TOOL_MORE_RU                    "доп. меню"

#define AXIS_X_ADD_TEXT_RU              "X +"
#define AXIS_X_DEC_TEXT_RU              "X -"
#define AXIS_Y_ADD_TEXT_RU              "Y +"
#define AXIS_Y_DEC_TEXT_RU              "Y -"
#define AXIS_Z_ADD_TEXT_RU              "Z +"
#define AXIS_Z_DEC_TEXT_RU              "Z -"
#define TEXT_01MM_RU                    "0.1 мм"
#define TEXT_1MM_RU                     "1 мм"
#define TEXT_10MM_RU                    "10 мм"

#define HOME_X_TEXT_RU                  "X"
#define HOME_Y_TEXT_RU                  "Y"
#define HOME_Z_TEXT_RU                  "Z"
#define HOME_ALL_TEXT_RU                "Дом"
#define HOME_STOPMOVE_RU                "Концевик"

#define PAGE_UP_TEXT_RU                 "вверх"
#define PAGE_DOWN_TEXT_RU               "вниз"

#define EXTRUDER_IN_TEXT_RU             "втянуть"
#define EXTRUDER_OUT_TEXT_RU            "вытянуть"
#define EXTRUDE_1MM_TEXT_RU             "1 мм"
#define EXTRUDE_5MM_TEXT_RU             "5 мм"
#define EXTRUDE_10MM_TEXT_RU            "10 мм"
#define EXTRUDE_LOW_SPEED_TEXT_RU       "минимум"
#define EXTRUDE_MEDIUM_SPEED_TEXT_RU    "средний"
#define EXTRUDE_HIGH_SPEED_TEXT_RU      "высокий"

#define LEVELING_POINT1_TEXT_RU         " 1 точка"
#define LEVELING_POINT2_TEXT_RU         " 2 точка"
#define LEVELING_POINT3_TEXT_RU         " 3 точка"
#define LEVELING_POINT4_TEXT_RU         " 4 точка"
#define LEVELING_POINT5_TEXT_RU         " 5 точка"

#define FILESYS_TEXT_RU                 "система"
#define WIFI_TEXT_RU                    "Wi-Fi"
#define FAN_TEXT_RU                     "вентилятор"
#define ABOUT_TEXT_RU                   "инфо"
#define BREAK_POINT_TEXT_RU             "продолжить"
#define FILAMENT_TEXT_RU                "замена"
#define LANGUAGE_TEXT_RU                "язык"
#define MOTOR_OFF_TEXT_RU               "откл. мотор"
#define MOTOR_OFF_XY_TEXT_RU            "откл. X и Y"
#define SHUTDOWN_TEXT_RU                "выключение"
#define MACHINE_PARA_RU                 "конфиг"

#define U_DISK_TEXT_RU                  "USB диск"
#define SD_CARD_TEXT_RU                 "SD диск"
#define WIFI_NAME_TEXT_RU               "Wi-Fi: "
#define WIFI_KEY_TEXT_RU                "пароль: "
#define WIFI_IP_TEXT_RU                 "IP: "
#define WIFI_AP_TEXT_RU                 "режим: AP"
#define WIFI_STA_TEXT_RU                "режим: STA"
#define WIFI_CONNECTED_TEXT_RU          "подключен"
#define WIFI_DISCONNECTED_TEXT_RU       "не подключен"
#define WIFI_EXCEPTION_TEXT_RU          "исключение"
#define WIFI_RECONNECT_TEXT_RU          "выбор сети"
#define CLOUD_TEXT_RU                   "облако"
#define CLOUD_BIND_RU                   "соединён"
#define CLOUD_UNBIND_RU                 "отсоед."
#define CLOUD_UNBINDING_RU              "отвязан"
#define CLOUD_DISCONNECTED_RU           "отключен"
#define CLOUD_UNBINDED_RU               "несвяз."
#define CLOUD_BINDED_RU                 "связан"
#define CLOUD_DISABLE_RU                "Disable"

#define FAN_ADD_TEXT_RU                 "увеличить"
#define FAN_DEC_TEXT_RU                 "уменьшить"
#define FAN_OPEN_TEXT_RU                "100 %"
#define FAN_HALF_TEXT_RU                "50 %"
#define FAN_CLOSE_TEXT_RU               "0 %"
#define FAN_TIPS1_TEXT_RU               "вентилятор"
#define FAN_TIPS2_TEXT_RU               "вентилятор\nоткл"

#define FILAMENT_IN_TEXT_RU             "втянуть"
#define FILAMENT_OUT_TEXT_RU            "вытянуть"
#define FILAMENT_EXT0_TEXT_RU           "экструдер 1"
#define FILAMENT_EXT1_TEXT_RU           "экструдер 2"
#define FILAMENT_HEAT_TEXT_RU           "нагрев"
#define FILAMENT_STOP_TEXT_RU           "стоп"
#define FILAMENT_TIPS2_TEXT_RU          "T: "
#define FILAMENT_TIPS3_TEXT_RU          "втянуть..."
#define FILAMENT_TIPS4_TEXT_RU          "вытянуть..."
#define FILAMENT_TIPS5_TEXT_RU          "Низкая температура, \nнеобходим нагрев"
#define FILAMENT_TIPS6_TEXT_RU          "завершён"

#define FILAMENT_CHANGE_TEXT_RU                       "Please click <Load> \nor <unload>,After \npinter pause."
#define FILAMENT_DIALOG_LOAD_HEAT_TIPS_RU             "Heating up the nozzle,\nplease wait..."
#define FILAMENT_DIALOG_UNLOAD_HEAT_TIPS_RU           "Heating up the nozzle,\nplease wait..."
#define FILAMENT_DIALOG_LOAD_CONFIRM1_TIPS_RU         "Heat completed,please load filament \nto extruder,and click <confirm> \nfor start loading."
#define FILAMENT_DIALOG_LOAD_CONFIRM2_TIPS_RU         "Please load filament to extruder,\nand click <confirm> for start loading."
#define FILAMENT_DIALOG_UNLOAD_CONFIRM_TIPS_RU        "Heat completed,please \nclick <confirm> for start unloading.!"
#define FILAMENT_DIALOG_LOADING_TIPS_RU               "Is loading, please wait!"
#define FILAMENT_DIALOG_UNLOADING_TIPS_RU             "Is unloading, please wait!"
#define FILAMENT_DIALOG_LOAD_COMPLETE_TIPS_RU         "Load filament completed,\nclick <confirm> for return!"
#define FILAMENT_DIALOG_UNLOAD_COMPLETE_TIPS_RU       "Unload filament completed,\nclick <confirm> for return!"

#define PRE_HEAT_EXT_TEXT_RU                "E"
#define PRE_HEAT_BED_TEXT_RU                "стол"

#define FILE_LOADING_RU                     "загрузка......"
#define NO_FILE_AND_CHECK_RU                "файл не найден!"

#define NO_FILE_RU                          "нет файла!"

#define EXTRUDER_TEMP_TEXT_RU               "температура"
#define EXTRUDER_E_LENGTH1_TEXT_RU          "экструдер 1"
#define EXTRUDER_E_LENGTH2_TEXT_RU          "экструдер 2"
#define EXTRUDER_E_LENGTH3_TEXT_RU          "экструдер 3"

#define ABOUT_TYPE_TEXT_RU                  "Type: "
#define ABOUT_VERSION_TEXT_RU               "Firmware: "
#define ABOUT_WIFI_TEXT_RU                  "Wi-Fi: "

#define PRINTING_OPERATION_RU               "опции"
#define PRINTING_PAUSE_RU                   "пауза"
#define PRINTING_TEMP_RU                    "темп"
#define PRINTING_CHANGESPEED_RU             "скорости"
#define PRINTING_RESUME_RU                  "возобн.   "
#define PRINTING_STOP_RU                    "стоп"
#define PRINTING_MORE_RU                    "больше"
#define PRINTING_EXTRUDER_RU                "экстр"
#define PRINTING_MOVE_RU                    "движение"

#define EXTRUDER_SPEED_RU                   "экстр"
#define MOVE_SPEED_RU                       "движ."
#define EXTRUDER_SPEED_STATE_RU             "скорость экстр"
#define MOVE_SPEED_STATE_RU                 "скорость движ"
#define STEP_1PERCENT_RU                    "1 %"
#define STEP_5PERCENT_RU                    "5 %"
#define STEP_10PERCENT_RU                   "10 %"

#define TITLE_READYPRINT_RU                 "готов к"
#define TITLE_PREHEAT_RU                    "движение"
#define TITLE_MOVE_RU                       "движение"
#define TITLE_HOME_RU                       "Home"
#define TITLE_EXTRUDE_RU                    "экструдер"
#define TITLE_LEVELING_RU                   "уровень"
#define TITLE_SET_RU                        "настройка"
#define TITLE_MORE_RU                       "больше"
#define TITLE_CHOOSEFILE_RU                 "файла"
#define TITLE_PRINTING_RU                   "печать"
#define TITLE_OPERATION_RU                  "управление"
#define TITLE_ADJUST_RU                     "регулировать"
#define TITLE_WIRELESS_RU                   "Wireless"
#define TITLE_FILAMENT_RU                   "замена"
#define TITLE_ABOUT_RU                      "информ."
#define TITLE_FAN_RU                        "вентилятор"
#define TITLE_LANGUAGE_RU                   "язык"
#define TITLE_PAUSE_RU                      "пауза"
#define TITLE_CHANGESPEED_RU                "скорости"
#define TILE_TOOL_RU                        "инструмент"
#define TITLE_CLOUD_TEXT_RU                 "Cloud"
#define TITLE_DIALOG_CONFIRM_RU             "Confirm"
#define TITLE_FILESYS_RU                    "FileSys"

#define AUTO_SHUTDOWN_RU                    "авто-откл"
#define MANUAL_SHUTDOWN_RU                  "ручн-откл"

#define DIALOG_CONFIRM_RU                   "да" // "подтвердить"
#define DIALOG_CANCLE_RU                    "отмена"
#define DIALOG_OK_RU                        "да"
#define DIALOG_RESET_RU                     "сброс"
#define DIALOG_RETRY_RU                     "повтор"
#define DIALOG_DISABLE_RU                   "запретить"
#define DIALOG_PRINT_MODEL_RU               "печать?"
#define DIALOG_CANCEL_PRINT_RU              "стоп?"
#define DIALOG_STOP_RU                      "стоп"
#define DIALOG_REPRINT_FROM_BREAKPOINT_RU   "продолжить?"
#define DIALOG_ERROR_TIPS1_RU               "ошибка: нет файла, попробуйте ещё раз."
#define DIALOG_ERROR_TIPS2_RU               "ошибка: сбой передачи. установите скорость \nпередачи данных как на плате управления!"
#define DIALOG_ERROR_TIPS3_RU               "ошибка: имя файла слишком длинное!"
#define DIALOG_CLOSE_MACHINE_RU             "Closing machine......"
#define DIALOG_UNBIND_PRINTER_RU            "Unbind the printer?"
#define DIALOG_FILAMENT_NO_PRESS_RU         "Filament detection switch is not pressed"
#define DIALOG_PRINT_FINISH_RU              "печать завершена!"
#define DIALOG_PRINT_TIME_RU                "Время печати: "
#define DIALOG_REPRINT_RU                   "повтор печати?"
#define DIALOG_WIFI_ENABLE_TIPS_RU          "The wifi module is being configured,\nplease wait a moment....."
#define DIALOG_AUTO_LEVELING_TIPS_RU        "Автоматическое выравнивание, подождите ..."

#define MESSAGE_PAUSING_RU            "Пауза"
#define MESSAGE_CHANGING_RU           "Подождите"
#define MESSAGE_UNLOAD_RU             "Дождитесь выгрузки нити"
#define MESSAGE_WAITING_RU            "Нажмите кнопку, чтобы\n возобновить печать"
#define MESSAGE_INSERT_RU             "Вставьте нить и нажмите кнопку,\nчтобы продолжить"
#define MESSAGE_LOAD_RU               "Дождитесь загрузки нити"
#define MESSAGE_PURGE_RU              "Дождитесь чистки нити"
#define MESSAGE_RESUME_RU             "Подождите, пока печать возобновится ..."
#define MESSAGE_HEAT_RU               "Нажмите кнопку, для нагрева сопла"
#define MESSAGE_HEATING_RU            "Подогрев сопла, подождите ..."
#define MESSAGE_OPTION_RU             "Очистить или продолжить печать?"
#define MESSAGE_PURGE_MORE_RU         "чистка"
#define MESSAGE_CONTINUE_PRINT_RU     "Печатать"
#define EEPROM_SETTINGS_TITLE_RU      "настройка EEPROM"
#define EEPROM_SETTINGS_STORE_RU      " Cохранение настроек в EEPROM"
#define EEPROM_SETTINGS_READ_RU       " Чтение настроек из EEPROM"
#define EEPROM_SETTINGS_REVERT_RU     " Bосстановить настройки по умолчанию"

#define MORE_CUSTOM1_TEXT_RU  MAIN_MENU_ITEM_1_DESC
#define MORE_CUSTOM2_TEXT_RU  MAIN_MENU_ITEM_2_DESC
#define MORE_CUSTOM3_TEXT_RU  MAIN_MENU_ITEM_3_DESC
#define MORE_CUSTOM4_TEXT_RU  MAIN_MENU_ITEM_4_DESC
#define MORE_CUSTOM5_TEXT_RU  MAIN_MENU_ITEM_5_DESC
#define MORE_CUSTOM6_TEXT_RU  MAIN_MENU_ITEM_6_DESC

#define EEPROM_STORE_TIPS_RU          "Cохранить в EEPROM?"
#define EEPROM_READ_TIPS_RU           "Восстановить из EEPROM?"
#define EEPROM_REVERT_TIPS_RU         "Cброс EEPROM по умолчанию?"
#define EEPROM_SETTINGS_RU            "EEPROM"

#define NEXT_RU                       "след."
#define PREVIOUS_RU                   "пред."
#define ENABLE_RU                     "да "
#define DISABLE_RU                    "нет"
#define KEY_CONFIRM_RU                "OK"

#define MACHINE_PARA_TITLE_RU          "настройка"
#define MACHINE_TYPE_CNOFIG_RU         " Hастройка принтера"
#define MOTOR_CONFIG_RU                " Hастройка моторов"
#define MACHINE_LEVELING_CONFIG_RU     " Hастройка уровня"
#define ADVANCE_CONFIG_RU              " Pасширенные настройки"
#define MACHINE_FILAMENT_CONFIG_RU     " Hастройка филамента"
#define ENCODER_SETTINGS_RU            " Hастройка энкодера"

#define LEVELING_CONF_TITLE_RU          "Hастройка принтера> Hастройка уровня"
#define LEVELING_PARA_CONF_RU           " настройка уровня"
#define TRAMMING_POS_RU                 " настройка координат для уровня"
#define LEVELING_AUTO_COMMAND_RU        " настройка комманд увтоуровня"
#define LEVELING_AUTO_ZOFFSET_RU        " координаты смещения сопла"

#define BLTOUCH_LEVELING_TITTLE_RU      "Hастройка>BL-Touch датчик"
#define BLTOUCH_LEVELING_RU             "BL-Touch датчик"
#define BLTOUCH_INIT_RU                 " иниц"
#define BLTOUCH_ZOFFSETPOS_RU           "Zoffset+"
#define BLTOUCH_ZOFFSETNEG_RU           "Zoffset-"
#define BLTOUCH_SAVE_RU                 " сохр."
#define BLTOUCH_TEST_RU                 " тест"

#define MACHINE_CONFIG_TITLE_RU         "Hастройка принтера> Параметры принтера"
#define MAXFEEDRATE_CONF_RU             " настройка максимальной скорости"
#define ACCELERATION_CONF_RU            " настройка ускорений"
#define JERKCONF_RU                     " настройка рывков"

#define MOTOR_CONF_TITLE_RU             "Hастройка принтера> Hастройка моторов"
#define STEPSCONF_RU                    " настройка шагов"
#define TMC_CURRENT_RU                  " TMC настройка токa"
#define TMC_STEP_MODE_RU                " TMC настройка режима шагов"

#define ACCELERATION_CONF_TITLE_RU      "Hастройка принтера> ускорения"
#define PRINT_ACCELERATION_RU           " ускорение печати"
#define RETRACT_ACCELERATION_RU         " ускорение ретракта"
#define TRAVEL_ACCELERATION_RU          " ускорение перемещений"
#define X_ACCELERATION_RU               " ускорение X мм/c"
#define Y_ACCELERATION_RU               " ускорение Y мм/c"
#define Z_ACCELERATION_RU               " ускорение Z мм/c"
#define E0_ACCELERATION_RU              " ускорение E0 мм/c"
#define E1_ACCELERATION_RU              " ускорение E1 мм/c"

#define MAXFEEDRATE_CONF_TITLE_RU       "Hастройка принтера> максимальная скорость"
#define X_MAXFEEDRATE_RU                " максимальная скорость X мм/с"
#define Y_MAXFEEDRATE_RU                " максимальная скорость Y мм/с"
#define Z_MAXFEEDRATE_RU                " максимальная скорость Z мм/с"
#define E0_MAXFEEDRATE_RU               " максимальная скорость E0 мм/с"
#define E1_MAXFEEDRATE_RU               " максимальная скорость E1 мм/с"

#define JERK_CONF_TITLE_RU              "Hастройка принтера> скорость рывка"
#define X_JERK_RU                       " скорость рывка X мм/с"
#define Y_JERK_RU                       " скорость рывка Y мм/с"
#define Z_JERK_RU                       " скорость рывка Z мм/с"
#define E_JERK_RU                       " скорость рывка E мм/с"

#define STEPS_CONF_TITLE_RU             "Hастройка принтера> настройка шагов"
#define X_STEPS_RU                      " шаг X шаг/мм"
#define Y_STEPS_RU                      " шаг Y шаг/мм"
#define Z_STEPS_RU                      " шаг Z шаг/мм"
#define E0_STEPS_RU                     " шаг E0 шаг/мм"
#define E1_STEPS_RU                     " шаг E1 шаг/мм"

#define TMC_CURRENT_CONF_TITLE_RU       "Hастройка принтера> TMC настройка токов"
#define X_TMC_CURRENT_RU                " ток X (mA)"
#define Y_TMC_CURRENT_RU                " ток Y (mA)"
#define Z_TMC_CURRENT_RU                " ток Z (mA)"
#define E0_TMC_CURRENT_RU               " ток E0 (mA)"
#define E1_TMC_CURRENT_RU               " ток E1 (mA)"

#define TMC_MODE_CONF_TITLE_RU          "Hастройка принтера> TMC настройка режима шагов"
#define X_TMC_MODE_RU                   " вкл. режим StealthChop X"
#define Y_TMC_MODE_RU                   " вкл. режим StealthChop Y"
#define Z_TMC_MODE_RU                   " вкл. режим StealthChop Z"
#define E0_TMC_MODE_RU                  " вкл. режим StealthChop E0"
#define E1_TMC_MODE_RU                  " вкл. режим StealthChop E1"

#define ADVANCED_CONF_TITLE_RU          "Hастройка принтера> Pасширенные"
#define PAUSE_POSITION_RU               " Hастройка позиции паузы печати"
#define PAUSE_POSITION_X_RU             " координата X (абс. полож., -1 недействит.)"
#define PAUSE_POSITION_Y_RU             " координата Y (абс. полож., -1 недействит.)"
#define PAUSE_POSITION_Z_RU             " координата Z (абс. полож., -1 недействит.)"

#define OFFSET_TITLE_RU                 "Hастройка принтера> отступ"
#define OFFSET_X_RU                     " отступ X мм"
#define OFFSET_Y_RU                     " отступ Y мм"
#define OFFSET_Z_RU                     " отступ Z мм"

#define FILAMENT_CONF_TITLE_RU          "Hастройка принтера> Hастройка филамента"
#define FILAMENT_IN_LENGTH_RU           " длина загрузки мм"
#define FILAMENT_IN_SPEED_RU            " скорость загрузки мм/с"
#define FILAMENT_TEMPERATURE_RU         " температура сопла ℃"
#define FILAMENT_OUT_LENGTH_RU          " длина извлечения мм"
#define FILAMENT_OUT_SPEED_RU           " скорость извлечения мм/с"

#define ENCODER_CONF_TITLE_RU           "Hастройка принтера> Hастройка энкодера"
#define ENCODER_CONF_TEXT_RU            " включить энкодер?"
